import { HuxleyDepartureBoard } from '../darwin-types';

export const darwinAllOnTime: HuxleyDepartureBoard = {
  generatedAt: '2026-03-05T07:48:00.000Z',
  locationName: 'Surbiton',
  crs: 'SUR',
  filterLocationName: 'London Waterloo',
  filtercrs: 'WAT',
  filterType: 1,
  delays: false,
  totalTrains: 4,
  totalTrainsDelayed: 0,
  totalDelayMinutes: 0,
  trainServices: [
    {
      std: '07:52',
      etd: 'On time',
      platform: '2',
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'abc123',
      serviceIdGuid: '11111111-1111-1111-1111-111111111111',
      serviceIdUrlSafe: 'abc123',
      rsid: 'SW111111',
      isCancelled: false,
      cancelReason: null,
      delayReason: null,
      length: '8',
      isCircularRoute: false,
    },
    {
      std: '08:07',
      etd: 'On time',
      platform: '2',
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'def456',
      serviceIdGuid: '22222222-2222-2222-2222-222222222222',
      serviceIdUrlSafe: 'def456',
      rsid: 'SW222222',
      isCancelled: false,
      cancelReason: null,
      delayReason: null,
      length: '8',
      isCircularRoute: false,
    },
    {
      std: '08:22',
      etd: 'On time',
      platform: '2',
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'ghi789',
      serviceIdGuid: '33333333-3333-3333-3333-333333333333',
      serviceIdUrlSafe: 'ghi789',
      rsid: 'SW333333',
      isCancelled: false,
      cancelReason: null,
      delayReason: null,
      length: '8',
      isCircularRoute: false,
    },
    {
      std: '08:37',
      etd: 'On time',
      platform: '2',
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'jkl012',
      serviceIdGuid: '44444444-4444-4444-4444-444444444444',
      serviceIdUrlSafe: 'jkl012',
      rsid: 'SW444444',
      isCancelled: false,
      cancelReason: null,
      delayReason: null,
      length: '8',
      isCircularRoute: false,
    },
  ],
  busServices: null,
  ferryServices: null,
  nrccMessages: null,
};

export const darwinWithDelays: HuxleyDepartureBoard = {
  generatedAt: '2026-03-05T07:48:00.000Z',
  locationName: 'Surbiton',
  crs: 'SUR',
  filterLocationName: 'London Waterloo',
  filtercrs: 'WAT',
  filterType: 1,
  delays: true,
  totalTrains: 4,
  totalTrainsDelayed: 3,
  totalDelayMinutes: 45,
  trainServices: [
    {
      std: '07:52',
      etd: '08:07',
      platform: '2',
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'abc123',
      serviceIdGuid: '11111111-1111-1111-1111-111111111111',
      serviceIdUrlSafe: 'abc123',
      rsid: 'SW111111',
      isCancelled: false,
      cancelReason: null,
      delayReason: 'Signal failure at Clapham Junction',
      length: '8',
      isCircularRoute: false,
    },
    {
      std: '08:07',
      etd: 'Delayed',
      platform: null,
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'def456',
      serviceIdGuid: '22222222-2222-2222-2222-222222222222',
      serviceIdUrlSafe: 'def456',
      rsid: 'SW222222',
      isCancelled: false,
      cancelReason: null,
      delayReason: 'Signal failure at Clapham Junction',
      length: '8',
      isCircularRoute: false,
    },
    {
      std: '08:22',
      etd: '08:37',
      platform: null,
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'ghi789',
      serviceIdGuid: '33333333-3333-3333-3333-333333333333',
      serviceIdUrlSafe: 'ghi789',
      rsid: 'SW333333',
      isCancelled: false,
      cancelReason: null,
      delayReason: 'Signal failure at Clapham Junction',
      length: '8',
      isCircularRoute: false,
    },
    {
      std: '08:37',
      etd: 'On time',
      platform: '2',
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'jkl012',
      serviceIdGuid: '44444444-4444-4444-4444-444444444444',
      serviceIdUrlSafe: 'jkl012',
      rsid: 'SW444444',
      isCancelled: false,
      cancelReason: null,
      delayReason: null,
      length: '8',
      isCircularRoute: false,
    },
  ],
  busServices: null,
  ferryServices: null,
  nrccMessages: null,
};

export const darwinMostCancelled: HuxleyDepartureBoard = {
  generatedAt: '2026-03-05T07:48:00.000Z',
  locationName: 'Surbiton',
  crs: 'SUR',
  filterLocationName: 'London Waterloo',
  filtercrs: 'WAT',
  filterType: 1,
  delays: true,
  totalTrains: 4,
  totalTrainsDelayed: 0,
  totalDelayMinutes: 0,
  trainServices: [
    {
      std: '07:52',
      etd: 'Cancelled',
      platform: null,
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'abc123',
      serviceIdGuid: '11111111-1111-1111-1111-111111111111',
      serviceIdUrlSafe: 'abc123',
      rsid: 'SW111111',
      isCancelled: true,
      cancelReason: 'A member of train crew being unavailable',
      delayReason: null,
      length: null,
      isCircularRoute: false,
    },
    {
      std: '08:07',
      etd: 'Cancelled',
      platform: null,
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'def456',
      serviceIdGuid: '22222222-2222-2222-2222-222222222222',
      serviceIdUrlSafe: 'def456',
      rsid: 'SW222222',
      isCancelled: true,
      cancelReason: 'A member of train crew being unavailable',
      delayReason: null,
      length: null,
      isCircularRoute: false,
    },
    {
      std: '08:22',
      etd: 'Cancelled',
      platform: null,
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'ghi789',
      serviceIdGuid: '33333333-3333-3333-3333-333333333333',
      serviceIdUrlSafe: 'ghi789',
      rsid: 'SW333333',
      isCancelled: true,
      cancelReason: 'A member of train crew being unavailable',
      delayReason: null,
      length: null,
      isCircularRoute: false,
    },
    {
      std: '08:37',
      etd: 'On time',
      platform: '2',
      operator: 'South Western Railway',
      operatorCode: 'SW',
      origin: [
        {
          locationName: 'Surbiton',
          crs: 'SUR',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      destination: [
        {
          locationName: 'London Waterloo',
          crs: 'WAT',
          via: null,
          futureChangeTo: null,
          assocIsCancelled: false,
        },
      ],
      serviceIdPercentEncoded: 'jkl012',
      serviceIdGuid: '44444444-4444-4444-4444-444444444444',
      serviceIdUrlSafe: 'jkl012',
      rsid: 'SW444444',
      isCancelled: false,
      cancelReason: null,
      delayReason: null,
      length: '8',
      isCircularRoute: false,
    },
  ],
  busServices: null,
  ferryServices: null,
  nrccMessages: null,
};

export const darwinNoServices: HuxleyDepartureBoard = {
  generatedAt: '2026-03-05T07:48:00.000Z',
  locationName: 'Surbiton',
  crs: 'SUR',
  filterLocationName: 'London Waterloo',
  filtercrs: 'WAT',
  filterType: 1,
  delays: false,
  totalTrains: 0,
  totalTrainsDelayed: 0,
  totalDelayMinutes: 0,
  trainServices: null,
  busServices: null,
  ferryServices: null,
  nrccMessages: null,
};
